version: '3.1'

services:
  app:
    depends_on:
      - database
    build:
      context: .
      dockerfile: Dockerfile
    image: app
    container_name: app
    restart: always
    ports:
      - "${PORT}:${PORT}"
    environment:
      PORT: ${PORT}

      DB_PORT: ${DB_PORT}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}

      CLOUDINARY_CLOUD_NAME: ${CLOUDINARY_CLOUD_NAME}
      CLOUDINARY_API_KEY: ${CLOUDINARY_API_KEY}
      CLOUDINARY_API_SECRET: ${CLOUDINARY_API_SECRET}
    volumes:
      - ./:/app

  database:
    image: postgres:14.5-alpine
    container_name: database
    restart: always
    ports:
      - ${DB_PORT}:5432
    environment:
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
    volumes:
      - ./database:/var/lib/postgresql/data
